[package]
name = "o3k-network"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
fabric-plan.workspace = true
fabric-linux.workspace = true
o3k-dhcp = { path = "../o3k-dhcp" }
o3k-domain = { path = "../o3k-domain" }
o3k-kernel = { path = "../o3k-kernel" }
o3k-store = { path = "../o3k-store" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
rustix = { workspace = true, features = ["fs"] }
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true

[dev-dependencies]
fabric-conformance.workspace = true
o3k-network-protocol = { path = "../o3k-network-protocol" }
sqlx = { workspace = true }
